version: '3.8'

services:
  user:
    build:
      context: ./ecomm-web
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env

  cart:
    build:
      context: ./ecomm-cart
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    env_file:
      - .env

  product:
    build:
      context: ./ecomm-product
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    env_file:
      - .env

  order:
    build:
      context: ./ecomm-order
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    env_file:
      - .env
