server:
  port: 8081
  servlet:
    context-path: /api

spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_URL}:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  elasticsearch:
    uris: ${ELASTICSEARCH_URL}
    password: ${ELASTICSEARCH_PASSWORD}
    username: elastic
    connection-timeout: 5s

logging:
  level:
    root: info

host:
  url: ${HOST_URL}

springdoc:
  swagger-ui:
    path: /swagger-ui
    enabled: true
  api-docs:
    enabled: true
    path: /api-docs